/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendeesRouteImport } from './routes/attendees'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as EventsRouteImport } from './routes/events'
import { Route as RegistrationsRouteImport } from './routes/registrations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesRoute = AttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendees': typeof AttendeesRoute
  '/create-event': typeof CreateEventRoute
  '/events': typeof EventsRoute
  '/registrations': typeof RegistrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendees': typeof AttendeesRoute
  '/create-event': typeof CreateEventRoute
  '/events': typeof EventsRoute
  '/registrations': typeof RegistrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendees': typeof AttendeesRoute
  '/create-event': typeof CreateEventRoute
  '/events': typeof EventsRoute
  '/registrations': typeof RegistrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendees' | '/create-event' | '/events' | '/registrations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendees' | '/create-event' | '/events' | '/registrations'
  id:
    | '__root__'
    | '/'
    | '/attendees'
    | '/create-event'
    | '/events'
    | '/registrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendeesRoute: typeof AttendeesRoute
  CreateEventRoute: typeof CreateEventRoute
  EventsRoute: typeof EventsRoute
  RegistrationsRoute: typeof RegistrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees': {
      id: '/attendees'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof AttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendeesRoute: AttendeesRoute,
  CreateEventRoute: CreateEventRoute,
  EventsRoute: EventsRoute,
  RegistrationsRoute: RegistrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
